### PR TITLE
Add Simplified Chinese translation

### PR DESCRIPTION
**Pull request by solitudechn**
Add Simplified Chinese translation

### CODE REVIEW

**Comment by nomi-san** [comment]
Thank you!

**Comment by solitudechn** [comment]
@nomi-san 


Hi, I'm trying to translate into Chinese and I found a problem I'd like to consult you about.
The original English name is "fallback_display". If it is directly translated into Chinese, the result is "回退显示" or "后备显示". These two Chinese meanings can roughly be understood as the first one, which means to revert something back to a previous version. The second one can be understood as the second display, or the non-primary display.
I downloaded the latest compiled version, and in the process of using it, I found that this translation is not accurate. May I ask, does it mean that when it is enabled, windows are not displayed actively? Or what does it mean?
I hope this question won't cause you any trouble. Thank you.

**Comment by nomi-san** [comment]
@solitudechn 

> Fallback display

This option lets the application automatically add a virtual display if your computer does not have a physical display (or just unplugged the last physical one). I was considering between "set as backup display" and "fallback display", but "fallback" was more meaning and shorter.

**Comment by solitudechn** [comment]
@nomi-san 

`没有物理显示器时自动添加虚拟显示器`

Considering the suggestions for language and readability, I think translating the Chinese phrase as "Automatically add a virtual display when there is no physical display" is a good choice. However, there is an issue with the current layout in the latest compiled version. Placing this option between "Boot on startup" and "Keep the screen on" may result in a visually unbalanced sequence due to the varying lengths of the phrases. Would you consider moving it to a different position or placing it on a separate line?

**Comment by nomi-san** [comment]
The tray menu was designed with submenu for the options, but when switching to WPF, it was buggy then moved it to top-level menu item. Lets wait for my feedback, Im finding an efficient way to bring the submenu back. If its impossible, just use a shorter text.

image

**Pull request merged**
